version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: lmscourse
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: